project_id = "fqppatxeddglmklobzow"

[functions.beta-signup]
verify_jwt = false

[functions.crypto-prices]
verify_jwt = true

[functions.crypto-list]
verify_jwt = false

[functions.stocks-list]
verify_jwt = false

[functions.lovable-chat]
verify_jwt = true

[functions.process-receipt]
verify_jwt = true