// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqppatxeddglmklobzow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxcHBhdHhlZGRnbG1rbG9iem93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5ODAzNzMsImV4cCI6MjA3MTU1NjM3M30.d0jkn9ZbOwFL111aekBePe_42LVQF5fCxpUW55hHL64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});